spring:
  application:
    name: rastreamento

  profiles:
    active: default

  datasource:
    url: jdbc:postgresql://localhost:5432/mottu
    username: mottu
    password: NovaSenha123!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5432/mottu
    user: mottu
    password: NovaSenha123!
    validate-on-migrate: false
    baseline-on-migrate: true

server:
  port: 8080
  address: 0.0.0.0

---
# Configuração para ambiente Docker
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:mysql://mysql:3306/mottu?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: mottu
    password: NovaSenha123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:mysql://mysql:3306/mottu?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    user: mottu
    password: NovaSenha123!
    validate-on-migrate: false
    baseline-on-migrate: true

