spring:
  application:
    name: rastreamento

server:
  port: 8080
  address: 0.0.0.0

---
# Configuração para ambiente Docker (MySQL gerenciado no Azure)
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:mysql://mottumysqlsrv.mysql.database.azure.com:3306/mottu?useSSL=true&requireSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&verifyServerCertificate=false
    username: mottuadmin
    password: FIAP@2tdsp!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:mysql://mottumysqlsrv.mysql.database.azure.com:3306/mottu?useSSL=true&requireSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&verifyServerCertificate=false
    user: mottuadmin
    password: FIAP@2tdsp!
    validate-on-migrate: false
    baseline-on-migrate: true
