spring:
  application:
    name: rastreamento

  datasource:
    url: jdbc:postgresql://localhost:5432/mottu
    username: mottu
    password: NovaSenha123!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5432/mottu
    user: mottu
    password: NovaSenha123!
    validate-on-migrate: false
    baseline-on-migrate: true

server:
  port: 8080
  address: 0.0.0.0
